### ISSUE TITLE
[DataGrid] React 18

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1870]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

This is an umbrella issue to keep track of the effort necessary toward supporting React 18. It might be painful.

## Details ✍️

- [ ] Broken column order #1562
- [ ] We can no longer measure renders with useEffect https://github.com/mui-org/material-ui/pull/26678

https://github.com/mui-org/material-ui-x/blob/45093913e390b9c71b89a3debf76a58a46e68a2f/packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx#L232-L241

**Comment by fahadashiq12** [comment]
Is MUI Data Grid Table compatible with React 18?

import { DataGridPro } from '@mui/x-data-grid-pro';
import { useDemoData } from '@mui/x-data-grid-generator';

I am installing both but doesn't work out..

**Comment by flaviendelangle** [comment]
@m4theushw I let you answer :+1:

**Comment by m4theushw** [comment]
The next release will be compatible with React 18.

**Comment by shivamchamoli09** [comment]
@m4theushw , @flaviendelangle  any updates on this release which is going to be for react 18 compatibility.

**Comment by flaviendelangle** [comment]
@shivamchamoli09 the DataGrid is compatible with React 18
This issue is only open because we need to migrate some of our tooling (the benchmarks mainly) to be compatible fully with React 18

**Comment by echorohit** [comment]
I am getting same error after moving to React 18
```2useGridRootProps.js:7 Uncaught Error: MUI: useGridRootProps should only be used inside the DataGrid, DataGridPro or DataGridPremium component.
    at useGridRootProps (useGridRootProps.js:7:1)
    at GridToolbarContainer (GridToolbarContainer.js:42:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)```
