### ISSUE TITLE
[DataGrid] First class support of v5

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1902]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 🔦

A list of tasks to do in order to drop @material-ui/core v4 and only support v5 going forward.

## Details

- [x] Wait for v5 to have enough [adoption](https://docs.google.com/spreadsheets/d/1KP94DulRRmUk2eBCWwhYQYIbL1wvoLFD0tKeLqeRH8c/edit#gid=609237852) -> 1/3 relative to v4 could be a great threshold to prioritize this effort.
- [x] Update docs, createMuiTheme->createTheme #2281
- [x] Migrate the docs and dev tooling to v5 two weeks before the stable release of v5. #2441 
- [ ] Remove `getDoc` prop. See https://github.com/mui-org/material-ui/pull/26696 for why. It solves our cross-document issue at the same time.  This is wrong ⬇️

https://github.com/mui-org/material-ui-x/blob/9dd5cf94061d1733566b7b66982fae554ebcf242/packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx#L28

First step in #2224

- [ ] Remove duplicated modules, for instance: https://github.com/mui-org/material-ui-x/blob/a4df486a95b72847224b71291fcdc3211feea3d1/packages/grid/_modules_/grid/utils/material-ui-utils.ts#L7
- [ ] Remove conditional code. #2575 
https://github.com/mui-org/material-ui-x/blob/1a0ad36f7380ba6bff04fa8f2b6366e001988734/packages/grid/_modules_/grid/components/GridPagination.tsx#L107
- [ ] Revert 36124c6?
- [x] Rename imports from @material-ui to @mui. #2571

**Comment by bestickley** [comment]
I have "@material-ui/core": "^5.0.0-beta.0" installed (along with peer deps) and "@material-ui/data-grid": "^4.0.0-alpha.33" installed. I'm getting the error:
```
error when starting dev server:
Error: Build failed with 1 error:
node_modules/@material-ui/data-grid/dist/index-esm.js:1:433: error: Could not resolve "@material-ui/styles" (mark it as external to exclude it from the bundle)
    at failureErrorWithLog (/Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:1449:15)
    at /Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:1236:14
    at /Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/stickb/Code/green-boost/starter/ui/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
```
Is this expected?

**Comment by embeddedt** [comment]
Any chance that https://github.com/mui-org/material-ui-x/commit/e1d572f7b3f4548cb6467b35aef3dc87ef962176 will land in a v4-compatible release?

**Comment by oliviertassinari** [comment]
@embeddedt Developers should be able to use MUI X v5 (the next version we work on) with @material-ui/core v4, with a bit of extra theme configuration. Would this be enough?

**Comment by embeddedt** [comment]
Yes; that would be perfect!
