### ISSUE TITLE
[DataGrid] Implement control state/prop for all props using useGridControlState hook

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#2044]
link to #190 

## Summary 💡

Following core work of #1823, we now have to bind all props with their onChange handler.
Todo includes:
-  [x] RegisterControlState for selection #1823
-  [x] RegisterControlState for filter #1909 
-  [x] RegisterControlState for SortModel #2095 
-  [x] RegisterControlState for pagination substates so one for page, one for pagesize #2099 
-  [x] RegisterControlState for editRowsModel #2143
- [ ] Cleanup, Remove redundant publishevent code, cleanup hook control mode, Fix publish event params (inconsistency btw callback and hook body)

**Comment by dtassone** [comment]
link to #190

**Comment by dtassone** [comment]
FYI I'm picking up control sort model

**Comment by flaviendelangle** [comment]
The `filterModel` is a single prop in `GridOptions`, which correspond to the `filter` key of the state.
But for the pagination, we don't have this equivalent.

The `pagination` state contains two different type of data.

### Descriptions of the rows 

- `paginationMode` which is coming from a prop (with a default fallback)
- `rowCount` which is coming from a prop if `paginationMode="server"` and from the `rows` (in which case it's a derived state)


### Descriptions of the current pagination

- `pageSize`
- `page`

For this part, we can have a controlled / uncontrolled behavior.
But unless the `filterModel`, these are two props, not a single `paginationModel` 

```ts
<Grid page={0} pageSize={20} />
```

Instead of 

```ts
<Grid paginationModel={{ page: 0, pageSize: 20 }} /> 
```

---

I think we want to split the state :

- the `paginationModel` part which can be controlled or uncontrolled
- the `rowCount` should not be derived stored in the state taken fril computed with the option or a selector

**Comment by flaviendelangle** [comment]
The `filterModel` is a single prop in `GridOptions`, which correspond to the `filter` key of the state.
But for the pagination, we don't have this equivalent, we have several options that either can or can't be controlled.

### Descriptions of the rows 

- `paginationMode` which is coming from a prop (with a default fallback)
- `rowCount` which is coming from a prop if `paginationMode="server"` and from the `rows` (in which case it's a derived state)


### Descriptions of the current pagination

- `pageSize`
- `page`

For this part, we can have a controlled / uncontrolled behavior.
But unless the `filterModel`, these are two props, not a single `paginationModel` 

```ts
<Grid page={0} pageSize={20} />
```

Instead of 

```ts
<Grid paginationModel={{ page: 0, pageSize: 20 }} /> 
```

---

To migrate to a behavior closer to the other controlled model, I propose to :

- Replace the `page` and `pageSize` options by a `paginationModel?: { page: number, pageSize: number }` which will be stored in the `pagination` state

If we do not want to do this breaking change, I can keep the 2 props and do a little bit a magic in `onChangeCallback` to decide which event to call. But this mean that the user can still give the `page` but not the `pageSize` and be in a semi-controlled mode, which is not great.

- Create a `useRowCount` hook that takes the `rowCount` from the options and the `apiRef` and returns the option `rowCount` if defined or the result of `visibleGridRowCountSelector` (this is the current behavior but right now the result is stored in the state in a `useEffect`, causing incoherent intermediate states (see https://github.com/mui-org/material-ui-x/issues/1815#issuecomment-872133196)

- Create a `usePageCount` hook that take the `rowCount` and the `apiRef` and returns the `pageCount`. 

- Remove `paginationMode` from the state and just add a default value `"client"` in `useOptionsProp`

**Comment by dtassone** [comment]
@flaviendelangle you just need to bind the props with their onChange events
so `page` with `onPageChange` , and `pageSize` with `onPageSizeChange`.
Then refactor the handlers to just take the props

```tsx
  onPageChange?: (page) => void;

  onPageSizeChange?: (pageSize) => void;
```

We don't need to control every prop, just the ones that have an onChange handler.

**Comment by flaviendelangle** [comment]
So you would do something like that ?

```tsx
  React.useEffect(() => {
    apiRef.current.updateControlState<GridFilterModel>({
      stateId: 'page',
      propModel: props.page,
      propOnChange: props.onPageChange,
      stateSelector: (state) => state.pagination.page,
      onChangeCallback: (model) => {
        apiRef.current.publishEvent(GRID_PAGE_CHANGE, model);
      },
    });
  }, [apiRef, props.page, props.onPageChange]);

  React.useEffect(() => {
    apiRef.current.updateControlState<GridFilterModel>({
      stateId: 'pageSize',
      propModel: props.pageSize,
      propOnChange: props.onPageSizeChange,
      stateSelector: (state) => state.pagination.pageSize,
      onChangeCallback: (model) => {
        apiRef.current.publishEvent(GRID_PAGE_SIZE_CHANGE, model);
      },
    });
  }, [apiRef, props.pageSize, props.onPageSizeChange]);
```

This won't fix [this](https://github.com/mui-org/material-ui-x/issues/1815#issuecomment-872133196]
But I suppose we can solve the two problem separetly.
I understood on the monday meeting that the control state/prop rework was supposed to solve this problem.

**Comment by oliviertassinari** [comment]
I'm closing as we have migrated all the controlled props.

**Comment by zubozrout** [comment]
Hello and apologize for spamming here,
however this new behaviour has made quite an impact on my little project and I am not sure how to workaround the server-side sorting with the new controlState `sortModel`.

I can give `DataGrid` anything, even a manually filled in `sortModel`. That works like a charm, but now when `onSortModelChange` calls my function that passes new settings to server it only briefly shows the respective data server returned and then in a blink of an eye reverts back to the original hard-coded `sortModel` that `DataGrid` has on load.

I also had a look at the "Story" tab here https://deploy-preview-2099--material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-sorting--server-side-sorting&globals=measureEnabled:false but sadly that didn't help me at all. If it is even relevant, not sure.

Could you please give me a very brief example/a few hints on how this is supposed to work now? That is how am I supposed to change the `sortModel` itself properly? Even if I have it as a state variable overwriting it inside `onSortModelChange` callback to whatever `DataGrid` returns only ends up with a never-ending loop.

Thank you very much for all your help.
